server.port=8080

# PostgreSQL Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=false

# JWT
app.jwt.secret=expense-tracker-super-secret-key-2024-minimum-256-bits-long
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=https://gudugudu.vercel.app,http://localhost:3000

logging.level.com.tracker=DEBUG
